### PR TITLE
updating src

### PR DESCRIPTION
**Pull request by maybuksho**

### CODE REVIEW

**Comment by sylus** [comment]
@blairdrummond what is this issue?

Can we have more descriptive messages other then "updating src"?

**Comment by maybuksho** [comment]
the programs in the src were out of date, so the pipeline was failed. Below are the src files updated
btap/src/config.py
btap/src/feature_selection.py
btap/src/plot.py
btap/src/predict.py
btap/src/preprocessing.py

**Comment by blairdrummond** [comment]
@sylus these are contrib containers, so these are user's own things. We'll just squash and let them merge if it passes scanning. (This is the only repo where they can add custom base images for pipelines)

**Comment by blairdrummond** [comment]
@maybuksho let me know when you want to merge

**Comment by maybuksho** [comment]
I am ready to merge, i pushed the changes

**Comment by maybuksho** [comment]
pls is the reference to the image still the same k8scc01covidacr.azurecr.io/btap:9e5e4a7afad16167292e242e1b5e36b1a46a1ec0

**Comment by sylus** [comment]
@blairdrummond that is fine lets just try as a standard to have more descriptive PRs :D

**Pull request merged**
